In [4]:
import numpy as np
import matplotlib.pyplot as plt 

Matrices

Matrices can be conceptulised in two ways.

Computer Science:

The computer science understanding of the matrix is an n dimensional array. i.e storing multiple arrays in a single data structure [1,2], bign the first array in the ds and [3.4] being the second. in computer science matrix are usually indexed by the following notation
matrix[row][column].

Mathematics:

In math specific to linear algebra matrices represent a linear transformation. These structures are n X m dimensions and transform vector belonging to one vector space to another. Matrices have the ability to stretch, rotate and even add extra dimensions to vectors. In math elements in a matrix are usally represent using the following notation A_ij, where A represents the matrix and i is the row index and j is the column index.

In [5]:
# Example matrices
# A 2x2 matrix (2 rows, 2 columns)
A = np.array([[1, 2],
              [3, 4]])

# A 2x3 matrix (2 rows, 3 columns)
B = np.array([[1, 2, 3],
              [4, 5, 6]])

# A 3x2 matrix (3 rows, 2 columns)
C = np.array([[1, 2],
              [3, 4],
              [5, 6]])

print("Matrix A (2x2):")
print(A)
print(f"\nShape: {A.shape}  (rows={A.shape[0]}, columns={A.shape[1]})")
print()

print("Matrix B (2x3):")
print(B)
print(f"\nShape: {B.shape}  (rows={B.shape[0]}, columns={B.shape[1]})")
print()

print("Matrix C (3x2):")
print(C)
print(f"\nShape: {C.shape}  (rows={C.shape[0]}, columns={C.shape[1]})")

Matrix A (2x2):
[[1 2]
 [3 4]]

Shape: (2, 2)  (rows=2, columns=2)

Matrix B (2x3):
[[1 2 3]
 [4 5 6]]

Shape: (2, 3)  (rows=2, columns=3)

Matrix C (3x2):
[[1 2]
 [3 4]
 [5 6]]

Shape: (3, 2)  (rows=3, columns=2)


Matrix Addition

In [6]:
# Example: A + B
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Matrix addition: add corresponding elements
result = A + B

print("Matrix A:")
print(A)
print()

print("Matrix B:")
print(B)
print()

print("A + B (add corresponding elements):")
print(result)
print()

# Show step by step
print("Step by step:")
print(f"A[0, 0] + B[0, 0] = {A[0, 0]} + {B[0, 0]} = {result[0, 0]}")
print(f"A[0, 1] + B[0, 1] = {A[0, 1]} + {B[0, 1]} = {result[0, 1]}")
print(f"A[1, 0] + B[1, 0] = {A[1, 0]} + {B[1, 0]} = {result[1, 0]}")
print(f"A[1, 1] + B[1, 1] = {A[1, 1]} + {B[1, 1]} = {result[1, 1]}")

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

A + B (add corresponding elements):
[[ 6  8]
 [10 12]]

Step by step:
A[0, 0] + B[0, 0] = 1 + 5 = 6
A[0, 1] + B[0, 1] = 2 + 6 = 8
A[1, 0] + B[1, 0] = 3 + 7 = 10
A[1, 1] + B[1, 1] = 4 + 8 = 12


Scalar Multiplication

In [7]:
# Example: 2 * A, 0.5 * A, -1 * A
A = np.array([[1, 2],
              [3, 4]])

A_doubled = 2 * A      # Multiply every element by 2
A_half = 0.5 * A       # Multiply every element by 0.5
A_negated = -1 * A     # Multiply every element by -1

print("Original matrix A:")
print(A)
print()

print("2 * A (double every element):")
print(A_doubled)
print()

print("0.5 * A (half every element):")
print(A_half)
print()

print("-1 * A (negate every element):")
print(A_negated)
print()

# Show step by step for 2 * A
print("Step by step for 2 * A:")
print(f"2 * {A[0, 0]} = {A_doubled[0, 0]}")
print(f"2 * {A[0, 1]} = {A_doubled[0, 1]}")
print(f"2 * {A[1, 0]} = {A_doubled[1, 0]}")
print(f"2 * {A[1, 1]} = {A_doubled[1, 1]}")

Original matrix A:
[[1 2]
 [3 4]]

2 * A (double every element):
[[2 4]
 [6 8]]

0.5 * A (half every element):
[[0.5 1. ]
 [1.5 2. ]]

-1 * A (negate every element):
[[-1 -2]
 [-3 -4]]

Step by step for 2 * A:
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8


Matrix Vector Multiplication

In [8]:
# Example: A × v
# A is 2×3, v is 3×1, result is 2×1
A = np.array([[1, 2, 3],
              [4, 5, 6]])

v = np.array([2, 3, 4])

# Matrix-vector multiplication
result = A @ v  # or np.dot(A, v)

print("Matrix A (2×3):")
print(A)
print()

print("Vector v (3×1):")
print(v)
print()

print("A × v (2×1 result):")
print(result)
print()

# Show step by step
print("Step by step calculation:")
print("For each row in A, multiply by v and sum:")
print()

row1 = A[0, :]
row2 = A[1, :]

print(f"First row of result:")
print(f"  A[0, :] · v = {row1[0]}*{v[0]} + {row1[1]}*{v[1]} + {row1[2]}*{v[2]}")
print(f"              = {row1[0]*v[0]} + {row1[1]*v[1]} + {row1[2]*v[2]}")
print(f"              = {result[0]}")
print()

print(f"Second row of result:")
print(f"  A[1, :] · v = {row2[0]}*{v[0]} + {row2[1]}*{v[1]} + {row2[2]}*{v[2]}")
print(f"              = {row2[0]*v[0]} + {row2[1]*v[1]} + {row2[2]*v[2]}")
print(f"              = {result[1]}")

Matrix A (2×3):
[[1 2 3]
 [4 5 6]]

Vector v (3×1):
[2 3 4]

A × v (2×1 result):
[20 47]

Step by step calculation:
For each row in A, multiply by v and sum:

First row of result:
  A[0, :] · v = 1*2 + 2*3 + 3*4
              = 2 + 6 + 12
              = 20

Second row of result:
  A[1, :] · v = 4*2 + 5*3 + 6*4
              = 8 + 15 + 24
              = 47


Matrix Matrix multiplication

In [9]:
# Example: A × B
# A is 2×3, B is 3×2, result is 2×2
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# Matrix-matrix multiplication
result = A @ B  # or np.dot(A, B)

print("Matrix A (2×3):")
print(A)
print()

print("Matrix B (3×2):")
print(B)
print()

print("A × B (2×2 result):")
print(result)
print()

# Show step by step
print("Step by step calculation:")
print("Each element C[i, j] = (row i of A) · (column j of B)")
print()

print(f"C[0, 0] = A[0, :] · B[:, 0]")
print(f"        = [{A[0, 0]}, {A[0, 1]}, {A[0, 2]}] · [{B[0, 0]}, {B[1, 0]}, {B[2, 0]}]")
print(f"        = {A[0, 0]}*{B[0, 0]} + {A[0, 1]}*{B[1, 0]} + {A[0, 2]}*{B[2, 0]}")
print(f"        = {A[0, 0]*B[0, 0]} + {A[0, 1]*B[1, 0]} + {A[0, 2]*B[2, 0]}")
print(f"        = {result[0, 0]}")
print()

print(f"C[0, 1] = A[0, :] · B[:, 1]")
print(f"        = [{A[0, 0]}, {A[0, 1]}, {A[0, 2]}] · [{B[0, 1]}, {B[1, 1]}, {B[2, 1]}]")
print(f"        = {A[0, 0]}*{B[0, 1]} + {A[0, 1]}*{B[1, 1]} + {A[0, 2]}*{B[2, 1]}")
print(f"        = {A[0, 0]*B[0, 1]} + {A[0, 1]*B[1, 1]} + {A[0, 2]*B[2, 1]}")
print(f"        = {result[0, 1]}")
print()

print(f"C[1, 0] = A[1, :] · B[:, 0]")
print(f"        = [{A[1, 0]}, {A[1, 1]}, {A[1, 2]}] · [{B[0, 0]}, {B[1, 0]}, {B[2, 0]}]")
print(f"        = {A[1, 0]}*{B[0, 0]} + {A[1, 1]}*{B[1, 0]} + {A[1, 2]}*{B[2, 0]}")
print(f"        = {A[1, 0]*B[0, 0]} + {A[1, 1]*B[1, 0]} + {A[1, 2]*B[2, 0]}")
print(f"        = {result[1, 0]}")
print()

print(f"C[1, 1] = A[1, :] · B[:, 1]")
print(f"        = [{A[1, 0]}, {A[1, 1]}, {A[1, 2]}] · [{B[0, 1]}, {B[1, 1]}, {B[2, 1]}]")
print(f"        = {A[1, 0]}*{B[0, 1]} + {A[1, 1]}*{B[1, 1]} + {A[1, 2]}*{B[2, 1]}")
print(f"        = {A[1, 0]*B[0, 1]} + {A[1, 1]*B[1, 1]} + {A[1, 2]*B[2, 1]}")
print(f"        = {result[1, 1]}")

Matrix A (2×3):
[[1 2 3]
 [4 5 6]]

Matrix B (3×2):
[[1 2]
 [3 4]
 [5 6]]

A × B (2×2 result):
[[22 28]
 [49 64]]

Step by step calculation:
Each element C[i, j] = (row i of A) · (column j of B)

C[0, 0] = A[0, :] · B[:, 0]
        = [1, 2, 3] · [1, 3, 5]
        = 1*1 + 2*3 + 3*5
        = 1 + 6 + 15
        = 22

C[0, 1] = A[0, :] · B[:, 1]
        = [1, 2, 3] · [2, 4, 6]
        = 1*2 + 2*4 + 3*6
        = 2 + 8 + 18
        = 28

C[1, 0] = A[1, :] · B[:, 0]
        = [4, 5, 6] · [1, 3, 5]
        = 4*1 + 5*3 + 6*5
        = 4 + 15 + 30
        = 49

C[1, 1] = A[1, :] · B[:, 1]
        = [4, 5, 6] · [2, 4, 6]
        = 4*2 + 5*4 + 6*6
        = 8 + 20 + 36
        = 64


Matrix transpose

Transposing a matrix: flip rows and columns! A transpose turns a m×n matrix into an n×m matrix. Notation: Aᵀ

In [10]:
# Example: A transpose
A = np.array([[1, 2, 3],
              [4, 5, 6]])

A_transpose = A.T  # or np.transpose(A)

print("Original matrix A (2×3):")
print(A)
print()

print("A transpose (3×2):")
print(A_transpose)
print()

# Show what happens
print("What happened:")
print(f"Row 0 of A [{A[0, 0]}, {A[0, 1]}, {A[0, 2]}] became column 0 of Aᵀ")
print(f"Row 1 of A [{A[1, 0]}, {A[1, 1]}, {A[1, 2]}] became column 1 of Aᵀ")
print()

print("Step by step:")
print(f"A[0, 0] = {A[0, 0]} → Aᵀ[0, 0] = {A_transpose[0, 0]}")
print(f"A[0, 1] = {A[0, 1]} → Aᵀ[1, 0] = {A_transpose[1, 0]}")
print(f"A[0, 2] = {A[0, 2]} → Aᵀ[2, 0] = {A_transpose[2, 0]}")
print(f"A[1, 0] = {A[1, 0]} → Aᵀ[0, 1] = {A_transpose[0, 1]}")
print(f"A[1, 1] = {A[1, 1]} → Aᵀ[1, 1] = {A_transpose[1, 1]}")
print(f"A[1, 2] = {A[1, 2]} → Aᵀ[2, 1] = {A_transpose[2, 1]}")
print()

print("Notice: (Aᵀ)ᵀ = A (transposing twice gives you back the original!)")
A_transpose_transpose = A_transpose.T
print(f"(Aᵀ)ᵀ = \n{A_transpose_transpose}")

Original matrix A (2×3):
[[1 2 3]
 [4 5 6]]

A transpose (3×2):
[[1 4]
 [2 5]
 [3 6]]

What happened:
Row 0 of A [1, 2, 3] became column 0 of Aᵀ
Row 1 of A [4, 5, 6] became column 1 of Aᵀ

Step by step:
A[0, 0] = 1 → Aᵀ[0, 0] = 1
A[0, 1] = 2 → Aᵀ[1, 0] = 2
A[0, 2] = 3 → Aᵀ[2, 0] = 3
A[1, 0] = 4 → Aᵀ[0, 1] = 4
A[1, 1] = 5 → Aᵀ[1, 1] = 5
A[1, 2] = 6 → Aᵀ[2, 1] = 6

Notice: (Aᵀ)ᵀ = A (transposing twice gives you back the original!)
(Aᵀ)ᵀ = 
[[1 2 3]
 [4 5 6]]


. Identity Matrix

The identity matrix I is special: when you multiply any matrix by I, you get back the same matrix! I has 1s on the diagonal and 0s everywhere else. A × I = A and I × A = A

In [11]:
# Example: Identity matrix
# 2×2 identity matrix
I2 = np.eye(2)  # or np.identity(2)

# 3×3 identity matrix
I3 = np.eye(3)

print("2×2 Identity matrix I:")
print(I2)
print()

print("3×3 Identity matrix I:")
print(I3)
print()

# Show that A × I = A
A = np.array([[1, 2],
              [3, 4]])

result = A @ I2

print("Matrix A:")
print(A)
print()

print("I × A (should equal A):")
print(result)
print()

print(f"A == I × A? {np.array_equal(A, result)}")
print()

# Show with a different matrix
B = np.array([[5, 6, 7],
              [8, 9, 10]])

print("Matrix B (2×3):")
print(B)
print()

print("B × I₃ (should equal B):")
print(B @ I3)
print()

print(f"B == B × I₃? {np.array_equal(B, B @ I3)}")
print()

print("Notice: The identity matrix acts like the number 1 in multiplication!")

2×2 Identity matrix I:
[[1. 0.]
 [0. 1.]]

3×3 Identity matrix I:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Matrix A:
[[1 2]
 [3 4]]

I × A (should equal A):
[[1. 2.]
 [3. 4.]]

A == I × A? True

Matrix B (2×3):
[[ 5  6  7]
 [ 8  9 10]]

B × I₃ (should equal B):
[[ 5.  6.  7.]
 [ 8.  9. 10.]]

B == B × I₃? True

Notice: The identity matrix acts like the number 1 in multiplication!


 Matrix Properties

Some important properties of matrices:

A + B = B + A (addition is commutative)
(A × B) × C = A × (B × C) (multiplication is associative)
A × (B + C) = A × B + A × C (distributive)
But A × B ≠ B × A in general! (multiplication is NOT commutative)

In [12]:
# Example: Matrix properties
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

C = np.array([[1, 0],
              [0, 1]])

print("Matrices:")
print("A =")
print(A)
print()

print("B =")
print(B)
print()

print("C =")
print(C)
print()

# Property 1: A + B = B + A
print("Property 1: A + B = B + A")
print(f"A + B = \n{A + B}")
print(f"B + A = \n{B + A}")
print(f"Equal? {np.array_equal(A + B, B + A)}")
print()

# Property 2: (A × B) × C = A × (B × C)
print("Property 2: (A × B) × C = A × (B × C)")
left = (A @ B) @ C
right = A @ (B @ C)
print(f"(A × B) × C = \n{left}")
print(f"A × (B × C) = \n{right}")
print(f"Equal? {np.array_equal(left, right)}")
print()

# Property 3: A × (B + C) = A × B + A × C
print("Property 3: A × (B + C) = A × B + A × C")
left = A @ (B + C)
right = A @ B + A @ C
print(f"A × (B + C) = \n{left}")
print(f"A × B + A × C = \n{right}")
print(f"Equal? {np.array_equal(left, right)}")
print()

# Property 4: A × B ≠ B × A (in general)
print("Property 4: A × B ≠ B × A (multiplication is NOT commutative!)")
AB = A @ B
BA = B @ A
print(f"A × B = \n{AB}")
print(f"B × A = \n{BA}")
print(f"Equal? {np.array_equal(AB, BA)}")
print("Notice: They're different! Order matters in matrix multiplication!")

Matrices:
A =
[[1 2]
 [3 4]]

B =
[[5 6]
 [7 8]]

C =
[[1 0]
 [0 1]]

Property 1: A + B = B + A
A + B = 
[[ 6  8]
 [10 12]]
B + A = 
[[ 6  8]
 [10 12]]
Equal? True

Property 2: (A × B) × C = A × (B × C)
(A × B) × C = 
[[19 22]
 [43 50]]
A × (B × C) = 
[[19 22]
 [43 50]]
Equal? True

Property 3: A × (B + C) = A × B + A × C
A × (B + C) = 
[[20 24]
 [46 54]]
A × B + A × C = 
[[20 24]
 [46 54]]
Equal? True

Property 4: A × B ≠ B × A (multiplication is NOT commutative!)
A × B = 
[[19 22]
 [43 50]]
B × A = 
[[23 34]
 [31 46]]
Equal? False
Notice: They're different! Order matters in matrix multiplication!


Common Matrix Operations Summary

Let's see different matrix operations side by side!

In [13]:
# Summary: Different matrix operations
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

v = np.array([2, 3])

print("Matrix A:")
print(A)
print()

print("Matrix B:")
print(B)
print()

print("Vector v:")
print(v)
print()

print("=" * 50)
print("OPERATIONS:")
print("=" * 50)
print()

print("1. Addition: A + B")
print(A + B)
print()

print("2. Scalar multiplication: 3 * A")
print(3 * A)
print()

print("3. Matrix-vector multiplication: A @ v")
print(A @ v)
print()

print("4. Matrix-matrix multiplication: A @ B")
print(A @ B)
print()

print("5. Transpose: A.T")
print(A.T)
print()

print("6. Element-wise multiplication (NOT matrix multiplication!): A * B")
print(A * B)
print("(This multiplies each corresponding element separately)")

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Vector v:
[2 3]

OPERATIONS:

1. Addition: A + B
[[ 6  8]
 [10 12]]

2. Scalar multiplication: 3 * A
[[ 3  6]
 [ 9 12]]

3. Matrix-vector multiplication: A @ v
[ 8 18]

4. Matrix-matrix multiplication: A @ B
[[19 22]
 [43 50]]

5. Transpose: A.T
[[1 3]
 [2 4]]

6. Element-wise multiplication (NOT matrix multiplication!): A * B
[[ 5 12]
 [21 32]]
(This multiplies each corresponding element separately)
